# Generated by Django 4.2.1 on 2023-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_copies_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_sold',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
