# Generated by Django 4.2.1 on 2023-05-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
