# Generated by Django 4.2.1 on 2023-05-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_category_book_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
    ]
